clear all
close all
clc

x1 = [0:.1:40];
y1 = 4.*cos(x1)./(x1+2);
x2 = [1:.2:20];
y2 = x2.^2./x2.^3;

figure(1); clf;
plot(x1, y1, x2, y2);

% box off
% set(gca, ...
%    'TickDir'     , 'out'     , ...
%    'XMinorTick'  , 'on'      , ...
%    'YMinorTick'  , 'on'      , ...
%    'XColor'      , [.2 .2 .2], ...
%    'YColor'      , [.2 .2 .2], ...
%    'fontsize', 8);
set(gca, ...
   'TickDir'     , 'out'     , ...
   'XMinorTick'  , 'on'      , ...
   'YMinorTick'  , 'on'      , ...
   'XColor'      , [.1 .1 .1], ...
   'YColor'      , [.1 .1 .1], ...
   'fontsize', 8);

xlabel('Speed (rpm) (-)', 'FontName', 'Segoe UI Symbol', 'fontsize', 8);
ylabel('Torque (Nm) (%)', 'FontName', 'Segoe UI Symbol', 'fontsize', 8);
title('Engine BSFC; \alpha = 10; (-)', 'FontName', 'Segoe UI Symbol', 'fontsize', 10, 'color', 'k');

text(5, 1, 'test (-)',  'FontName', 'Segoe UI Symbol', 'fontsize', 10);
defaultratio;

export_fig test_export_font -painters

